# Generated by Django 3.0.8 on 2020-08-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
