# Generated by Django 3.0.8 on 2020-08-09 14:57

from django.db import migrations
import editorjs_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='text',
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=editorjs_field.fields.EditorJSField(blank=True),
        ),
    ]
