# Generated by Django 3.0.8 on 2020-08-09 15:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200809_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
